import numpy as np
import matplotlib.pyplot as plt
import json
import os
from dotenv import load_dotenv
import time

# IBM WatsonX imports
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import (
    ModelTypes,
    DecodingMethods,
)

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

load_dotenv()

### 1.1: Define the file_path to the text file
file_path = 'California-Culinary-Map.txt'

### 1.2: Open the text file
with open(file_path, 'r') as file:
    text_content = file.read()

### 1.3: Print the first 100 characters of the restaurant data
#print(text_content[:100])

### 2.1: Split the restaurant paragraphs into list (hint: use .split)
restaurant_list = text_content.split('\n\n')

### 2.2: Since the first item is the dataset name, we remove it
restaurant_list = restaurant_list[1:]

### 2.3: Print out the number of restaurants we have
#print(f"Number of restaurants: {len(restaurant_list)}")

### 2.4: Print out the first item to have a closer look at the content
#print(restaurant_list[0])

def llm_model(system_msg, prompt_txt):
    #system_msg: the system message given to the LLM
    #prompt_txt: the user prompt
    
    model_id = "ibm/granite-4-h-small"
    project_id=os.getenv('WATSONX_PROJECT_ID')
    credentials = Credentials(url = "https://us-south.ml.cloud.ibm.com"
                              , api_key =os.getenv('WATSONX_API_KEY'))

    ### 1.1: Define the model by ModelInference
    model = ModelInference(
        model_id=model_id,
        project_id=project_id,
        credentials=credentials
    )

    ### 1.2: Define the messages
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": prompt_txt}
    ]

    ### 1.3: Get the final response output and return it
    response = model.chat(messages=messages)
    final_output = response["choices"][0]["message"]["content"]
    return final_output

def safe_llm_call(system_msg, prompt_txt, retries=3):
    for i in range(retries):
        try:
            return llm_model(system_msg, prompt_txt)
        except Exception:
            time.sleep(2)
    return "Failed after retries"

system_msg = "You are a helpful assistant."
prompt_txt = "Which place is warmer in winter? Hawaii or Greenland?"
print(safe_llm_call(system_msg, prompt_txt))
#print(llm_model(system_msg, prompt_txt))