import numpy as np
import matplotlib.pyplot as plt
import json
import os
from dotenv import load_dotenv
import time
from pydantic import BaseModel, Field, ValidationError
from typing import List, Optional

# IBM WatsonX imports
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import (
    ModelTypes,
    DecodingMethods,
)
import zipfile
import base64
from io import BytesIO
import ast # needed to convert string representation of list to actual python list
import requests
from tenacity import retry, stop_after_attempt, wait_exponential

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

load_dotenv()

with zipfile.ZipFile("data/synthetic-recipe-images.zip", 'r') as zip_ref:
    zip_ref.extractall("data")

### Step 1.1: Load the json file. Define the loaded data as recipe_data.
with open('data/Recipes.json', 'r') as file:
    recipe_data = json.load(file)

# ### Step 1.2: Print each key-value pair of the first recipe. In this format: key (type of value): value
# for key, value in recipe_data[0].items():
#     print(f"{key} ({type(value)}): {value}")

### Step 1.3: Show the image of the first recipe (recipe1)
recipe_id = recipe_data[0]['id']
image_path = os.path.join('data', 'synthetic_recipe_images', f'recipe{recipe_id}.png')
# plt.imshow(plt.imread(image_path))
# plt.axis('off')
# plt.show()

### Your Code Here: Fill in the blanks
def vision_llm(system_msg, prompt_txt, image_path):
    #system_msg: input system message for the LLM
    #prompt_txt: input user prompt for the LLM
    #image_path: the file path of the input image

    ### Credentials of the model
    model_id = 'meta-llama/llama-4-maverick-17b-128e-instruct-fp8'
    project_id=os.getenv('WATSONX_PROJECT_ID')
    credentials = Credentials(url = "https://us-south.ml.cloud.ibm.com"
                              , api_key =os.getenv('WATSONX_API_KEY'))
    generate_params = {"max_tokens": 300}

    ### Step 2.1: Define the model by ModelInference
    model = ModelInference(
        model_id=model_id,
        project_id=project_id,
        credentials=credentials,
        params=generate_params
    )
    

    ### Step 2.2: Encode the input image to a base64 string
    with open(image_path, "rb") as file:
        image_data = file.read()
    encoded_image = base64.b64encode(image_data).decode("utf-8")
    
    # Determine MIME type from file extension
    file_ext = os.path.splitext(image_path)[1].lower()
    mime_type = "image/png" if file_ext == ".png" else "image/jpeg" if file_ext in [".jpg", ".jpeg"] else "image/png"
    
    # Format as a proper data URL
    image_data_url = f"data:{mime_type};base64,{encoded_image}"
    
    

    ### Step 2.3: Define the messages for the model
    messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt_txt},
                        {"type": "image_url", "image_url": {"url": image_data_url}}
                    ],
                }
            ]
    

    ### Step 2.4: Get the response for the messages
    response = model.chat(
        messages=messages,
        params=generate_params
    )

    final_output = response["choices"][0]["message"]["content"]
    return final_output

# # Example of using the vision_llm function
# system_message = "You are a helpful assistant for cooking. You will be given a recipe image and a question about the recipe. Please answer the question based on the image content."
# user_prompt = "What are the ingredients for this recipe?"
# image_path = os.path.join('data', 'synthetic_recipe_images', 'recipe1.png')
# answer = vision_llm(system_message, user_prompt, image_path)

### Define the food image caption prompts given a food name.
### The food name, as you have noticed, comes from the corresponding recipe data.
### You want to include the food name to ensure the model focuses on it while giving captions.
def image_caption_prompt_template(food_name):
    # food_name: the food name of the recipe

    ### Step 3.1: Design the prompts
    image_caption_system_msg = f"You are a helpful assistant for cooking. You will be given an image of {food_name}. Please provide a detailed caption for the image."
    image_caption_prompt_txt = f"Describe the {food_name} in the image."

    return image_caption_system_msg, image_caption_prompt_txt

### Test the prompts on the first recipe
### Step 3.2: Get the prompts with the food name of the first recipe
first_recipe_food_name = recipe_data[0]['name']
system_msg, prompt_txt = image_caption_prompt_template(first_recipe_food_name)

## Step 3.3: Get the test response and print it
response = vision_llm(system_msg, prompt_txt, image_path)
# print(response)

# ### Get captions for each image in the dataset and add to the JSON file (up tp 15 minutes)
# ### recipe_data is the recipe you loaded in Step 1
# for i in range(len(recipe_data)):
#     if (i+1)%20 == 0:
#         print(f'{i+1} out of {len(recipe_data)} is done')

#     ### Step 4.1: Get the caption prompts
#     food_name = recipe_data[i]['name']
#     system_msg, prompt_txt = image_caption_prompt_template(food_name)

#     ### Step 4.2: Get the response with the prompts
#     image_path = os.path.join('data', 'synthetic_recipe_images', f'recipe{recipe_data[i]["id"]}.png')
#     response = vision_llm(system_msg, prompt_txt, image_path)

#     ### Save the response as another item in the recipe data
#     recipe_data[i]['image_description'] = response
# print('ALL DONE!')

#================
### Step 1.1: Load the review dataset with variable name user_review_data
with open('data/Synthetic-User-Reviews.json', 'r') as file:
    user_review_data = json.load(file)

### Step 1.2: Print the first review by key-value pairs
for key, value in user_review_data[0].items():
    print(f"{key} ({type(value)}): {value}")

### Convert the list of images of the first user into the actual python list
### Step 1.3: Use ast.literal_eval to convert
user_review_data[0]['images'] = ast.literal_eval(user_review_data[0]['images'])

### Step 1.4: Use the requests.get() method to get the image content
image_url = user_review_data[0]['images'][0]
response = requests.get(image_url)

### Step 1.5: Write the image content in Step 1.4 to a temporary file 'review_image_placeholder.jpg'
with open('review_image_placeholder.jpg', 'wb') as f:
    f.write(response.content)

### Step 1.6: Open the 'review_image_placeholder.jpg', and show th image
# img = plt.imread('review_image_placeholder.jpg')
# plt.imshow(img) 


### Prompt template: caption the images with the context of the reviews
def review_context_image_caption_prompt_template(reviews):
    # reviews: the written review content


    ### Step 2.1: Design your prompts
    # you will design a prompt template for the vision task and perform a unit test to validate the model’s behavior. However, unlike the previous exercise, this prompt must incorporate textual context from user reviews to guide the image captioning process.
    # In this step, you will define a prompt template function that takes user review text as input and uses it as contextual information when describing a food image. The system message assigns the model the role of a culinary expert, while the prompt instructs the model to generate a concise image description that aligns with the sentiment and details expressed in the reviews.
    # After defining the prompt template, you will perform a unit test by running the vision LLM on a single image and its associated reviews. This test allows you to verify that the generated caption effectively combines visual information from the image with contextual cues from the reviews before applying the prompt at scale in later steps.
    review_context_image_caption_system_msg = f"You are a culinary expert and a helpful assistant for cooking. You will be given an image of a dish and some user reviews about the dish. Please provide a concise description for the image based on the visual content and the context from the reviews. The description should reflect the sentiment and details expressed in the reviews while accurately describing the food in the image."
    review_context_image_caption_prompt_txt = f"Describe the dish in the image based on the reviews: {reviews}" 

    return review_context_image_caption_system_msg, review_context_image_caption_prompt_txt 

### Step 2.2: Get the prompts
first_review_text = user_review_data[0]['text']
system_msg, prompt_txt = review_context_image_caption_prompt_template(first_review_text)    

### Step 2.3: Get the response by the vision_llm you defined previously
response = vision_llm(system_msg, prompt_txt, 'review_image_placeholder.jpg')
# print(response)

### URL Request function with Retry
# Retries up to 10 times, starting at 1s and doubling (1s, 2s, 4s...)
@retry(stop=stop_after_attempt(10), wait=wait_exponential(multiplier=1, min=1, max=10))
def get_data_with_retry(url):
    response = requests.get(url, timeout=5)
    response.raise_for_status() # Must raise error for retry to trigger
    return response

### Start the for loop
for i in range(len(user_review_data)):
    ### Step 3.1: Get the list of image urls from the 'images' column
    #example images: ['https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/L0HyLOGuAlxwKZaCC8sJdg/Gemini-Generated-Image-523rkg523rkg523r.png','https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/YLCD9AYY985XxvP-K8CRbA/Gemini-Generated-Image-hy4y8why4y8why4y.png']
    # The data is already parsed from JSON, so images is already a list
    review_images = (
        user_review_data[i]['images']
        if isinstance(user_review_data[i]['images'], list)
        else ast.literal_eval(user_review_data[i]['images'])
    )

    review_image_captions = []
    if len(review_images) > 0:
        for img_url in review_images:
            try:
                ### Step 3.2: Use get_data_with_retry to get the image_data
                image_data = get_data_with_retry(img_url)
                print("Success!")
            except Exception as e:
                print(f"All retries failed at url {img_url}:", e)
                continue
            image = image_data.content
            with open('review_image_placeholder.jpg', 'wb') as img_file:
                img_file.write(image)

            ### Step 3.3: Get the prompts, get the response, and finally append the response to review_image_captions
            review_text = user_review_data[i]['text']
            system_msg, prompt_txt = review_context_image_caption_prompt_template(review_text)
            caption = vision_llm(system_msg, prompt_txt, 'review_image_placeholder.jpg')
            review_image_captions.append(caption)  
    
    ### Append the review_image_captions to the review data
    user_review_data[i]['image_captions'] = review_image_captions
print('ALL DONE!')

filename = 'augmented_user_review.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(user_review_data, f, indent=4)